<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>DXRDemo</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Direct3D.DXC" Version="1.9.2602.24" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shaders\DXR\**\*.hlsl" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Shaders\DXR\**\*.hlsli" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <Microsoft_Direct3D_DXC_SkipLibraryCopy>true</Microsoft_Direct3D_DXC_SkipLibraryCopy>
    <_DxcSourceArch Condition="'$(PlatformTarget)' == 'x86' Or '$(RuntimeIdentifier)' == 'win-x86'">x86</_DxcSourceArch>
    <_DxcSourceArch Condition="'$(PlatformTarget)' == 'ARM64' Or '$(RuntimeIdentifier)' == 'win-arm64'">arm64</_DxcSourceArch>
    <_DxcSourceArch Condition="'$(PlatformTarget)' == 'x64' Or '$(RuntimeIdentifier)' == 'win-x64'">x64</_DxcSourceArch>
    <_DxcSourceDir Condition="'$(_DxcSourceArch)' != ''">$([MSBuild]::NormalizePath('$(NuGetPackageRoot)', 'microsoft.direct3d.dxc', '1.9.2602.24', 'build', 'native', 'bin', '$(_DxcSourceArch)'))</_DxcSourceDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(_DxcSourceArch)' != ''">
    <None Include="$(_DxcSourceDir)\dxc.exe" Link="dxc.exe" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(_DxcSourceDir)\dxcompiler.dll" Link="dxcompiler.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(_DxcSourceDir)\dxil.dll" Link="dxil.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">False</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\Models\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ComputeSharp" Version="3.2.0" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.6.2" />
    <PackageReference Include="WinUIEx" Version="2.9.2" />
  </ItemGroup>
</Project>